---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: centos-7
    hostname: centos-7
    image: centos:7
  - name: fedora-26
    hostname: fedora-26
    image: fedora:26
    # this is what is used by jenkins rdo slaves cand proved to be different
    # enough regarding yum/dnf behavior.
  - name: fedora-28
    hostname: fedora-28
    image: fedora:28
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
